export interface Book {
  id: number;       // 1-66
  name: string;     // Korean name
  nameEn: string;   // English name (KJV)
  chapters: number; // chapter count
  testament: 'old' | 'new';
}

export const BOOKS: Book[] = [
  // Old Testament (1-39)
  { id: 1,  name: '창세기',     nameEn: 'Genesis',         chapters: 50, testament: 'old' },
  { id: 2,  name: '출애굽기',   nameEn: 'Exodus',          chapters: 40, testament: 'old' },
  { id: 3,  name: '레위기',     nameEn: 'Leviticus',       chapters: 27, testament: 'old' },
  { id: 4,  name: '민수기',     nameEn: 'Numbers',         chapters: 36, testament: 'old' },
  { id: 5,  name: '신명기',     nameEn: 'Deuteronomy',     chapters: 34, testament: 'old' },
  { id: 6,  name: '여호수아',   nameEn: 'Joshua',          chapters: 24, testament: 'old' },
  { id: 7,  name: '사사기',     nameEn: 'Judges',          chapters: 21, testament: 'old' },
  { id: 8,  name: '룻기',       nameEn: 'Ruth',            chapters:  4, testament: 'old' },
  { id: 9,  name: '사무엘상',   nameEn: '1 Samuel',        chapters: 31, testament: 'old' },
  { id: 10, name: '사무엘하',   nameEn: '2 Samuel',        chapters: 24, testament: 'old' },
  { id: 11, name: '열왕기상',   nameEn: '1 Kings',         chapters: 22, testament: 'old' },
  { id: 12, name: '열왕기하',   nameEn: '2 Kings',         chapters: 25, testament: 'old' },
  { id: 13, name: '역대상',     nameEn: '1 Chronicles',    chapters: 29, testament: 'old' },
  { id: 14, name: '역대하',     nameEn: '2 Chronicles',    chapters: 36, testament: 'old' },
  { id: 15, name: '에스라',     nameEn: 'Ezra',            chapters: 10, testament: 'old' },
  { id: 16, name: '느헤미야',   nameEn: 'Nehemiah',        chapters: 13, testament: 'old' },
  { id: 17, name: '에스더',     nameEn: 'Esther',          chapters: 10, testament: 'old' },
  { id: 18, name: '욥기',       nameEn: 'Job',             chapters: 42, testament: 'old' },
  { id: 19, name: '시편',       nameEn: 'Psalms',          chapters: 150, testament: 'old' },
  { id: 20, name: '잠언',       nameEn: 'Proverbs',        chapters: 31, testament: 'old' },
  { id: 21, name: '전도서',     nameEn: 'Ecclesiastes',    chapters: 12, testament: 'old' },
  { id: 22, name: '아가',       nameEn: 'Song of Solomon', chapters:  8, testament: 'old' },
  { id: 23, name: '이사야',     nameEn: 'Isaiah',          chapters: 66, testament: 'old' },
  { id: 24, name: '예레미야',   nameEn: 'Jeremiah',        chapters: 52, testament: 'old' },
  { id: 25, name: '예레미야애가', nameEn: 'Lamentations',  chapters:  5, testament: 'old' },
  { id: 26, name: '에스겔',     nameEn: 'Ezekiel',         chapters: 48, testament: 'old' },
  { id: 27, name: '다니엘',     nameEn: 'Daniel',          chapters: 12, testament: 'old' },
  { id: 28, name: '호세아',     nameEn: 'Hosea',           chapters: 14, testament: 'old' },
  { id: 29, name: '요엘',       nameEn: 'Joel',            chapters:  3, testament: 'old' },
  { id: 30, name: '아모스',     nameEn: 'Amos',            chapters:  9, testament: 'old' },
  { id: 31, name: '오바댜',     nameEn: 'Obadiah',         chapters:  1, testament: 'old' },
  { id: 32, name: '요나',       nameEn: 'Jonah',           chapters:  4, testament: 'old' },
  { id: 33, name: '미가',       nameEn: 'Micah',           chapters:  7, testament: 'old' },
  { id: 34, name: '나훔',       nameEn: 'Nahum',           chapters:  3, testament: 'old' },
  { id: 35, name: '하박국',     nameEn: 'Habakkuk',        chapters:  3, testament: 'old' },
  { id: 36, name: '스바냐',     nameEn: 'Zephaniah',       chapters:  3, testament: 'old' },
  { id: 37, name: '학개',       nameEn: 'Haggai',          chapters:  2, testament: 'old' },
  { id: 38, name: '스가랴',     nameEn: 'Zechariah',       chapters: 14, testament: 'old' },
  { id: 39, name: '말라기',     nameEn: 'Malachi',         chapters:  4, testament: 'old' },
  // New Testament (40-66)
  { id: 40, name: '마태복음',   nameEn: 'Matthew',         chapters: 28, testament: 'new' },
  { id: 41, name: '마가복음',   nameEn: 'Mark',            chapters: 16, testament: 'new' },
  { id: 42, name: '누가복음',   nameEn: 'Luke',            chapters: 24, testament: 'new' },
  { id: 43, name: '요한복음',   nameEn: 'John',            chapters: 21, testament: 'new' },
  { id: 44, name: '사도행전',   nameEn: 'Acts',            chapters: 28, testament: 'new' },
  { id: 45, name: '로마서',     nameEn: 'Romans',          chapters: 16, testament: 'new' },
  { id: 46, name: '고린도전서', nameEn: '1 Corinthians',   chapters: 16, testament: 'new' },
  { id: 47, name: '고린도후서', nameEn: '2 Corinthians',   chapters: 13, testament: 'new' },
  { id: 48, name: '갈라디아서', nameEn: 'Galatians',       chapters:  6, testament: 'new' },
  { id: 49, name: '에베소서',   nameEn: 'Ephesians',       chapters:  6, testament: 'new' },
  { id: 50, name: '빌립보서',   nameEn: 'Philippians',     chapters:  4, testament: 'new' },
  { id: 51, name: '골로새서',   nameEn: 'Colossians',      chapters:  4, testament: 'new' },
  { id: 52, name: '데살로니가전서', nameEn: '1 Thessalonians', chapters: 5, testament: 'new' },
  { id: 53, name: '데살로니가후서', nameEn: '2 Thessalonians', chapters: 3, testament: 'new' },
  { id: 54, name: '디모데전서', nameEn: '1 Timothy',       chapters:  6, testament: 'new' },
  { id: 55, name: '디모데후서', nameEn: '2 Timothy',       chapters:  4, testament: 'new' },
  { id: 56, name: '디도서',     nameEn: 'Titus',           chapters:  3, testament: 'new' },
  { id: 57, name: '빌레몬서',   nameEn: 'Philemon',        chapters:  1, testament: 'new' },
  { id: 58, name: '히브리서',   nameEn: 'Hebrews',         chapters: 13, testament: 'new' },
  { id: 59, name: '야고보서',   nameEn: 'James',           chapters:  5, testament: 'new' },
  { id: 60, name: '베드로전서', nameEn: '1 Peter',         chapters:  5, testament: 'new' },
  { id: 61, name: '베드로후서', nameEn: '2 Peter',         chapters:  3, testament: 'new' },
  { id: 62, name: '요한일서',   nameEn: '1 John',          chapters:  5, testament: 'new' },
  { id: 63, name: '요한이서',   nameEn: '2 John',          chapters:  1, testament: 'new' },
  { id: 64, name: '요한삼서',   nameEn: '3 John',          chapters:  1, testament: 'new' },
  { id: 65, name: '유다서',     nameEn: 'Jude',            chapters:  1, testament: 'new' },
  { id: 66, name: '요한계시록', nameEn: 'Revelation',      chapters: 22, testament: 'new' },
];

export const TOTAL_CHAPTERS = BOOKS.reduce((sum, b) => sum + b.chapters, 0); // 1,189
